name: Run UnitTests
on: push

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Unit tests
        shell: pwsh
        run: |
          ./tools/runTests.ps1
